apiVersion: v1
kind: Service
metadata:
  name: splunk-service
  namespace: lansplunk
  annotations:
    metallb.universe.tf/address-pool: loadbalanced
spec:
  type: LoadBalancer
  selector:
    app: splunk
  ports:
  - port: 80
    targetPort: 8000
