apiVersion: v1
kind: Service
metadata:
  name: syslog-service
  namespace: lansplunk

spec:
  type: NodePort
  selector:
    app: splunk
  ports:
  - port: 5514
    targetPort: 514
    protocol: UDP
    nodePort: 31673